<template>
  <view class="page"><AppNavBar title="学习平台规则" :show-back="true" /><scroll-view scroll-y class="content"><view class="hero"><text>接单避免踩坑</text><text>熟记平台规则</text><text>多接高价好单</text></view><view class="intro">以下为快马新手零工必学注意事项及平台规则，<text>请在测试前认真学习。</text></view><view class="pill">{{ course.title || "接单全流程注意事项" }}</view><view v-if="loading" class="state">规则内容加载中…</view><view v-else-if="!sections.length" class="state">后台暂未发布学习规则</view><view v-else v-for="(section,index) in sections" :key="index" class="section"><text class="section-title">{{ section.title || `学习内容 ${index + 1}` }}</text><rich-text v-if="section.html" :nodes="section.html" class="section-body" /><text v-else class="section-body">{{ section.content }}</text></view></scroll-view><SafeBottomAction><button class="done" @click="complete">我已学习完成</button></SafeBottomAction></view>
</template>
<script setup>
import { onMounted, ref } from "vue";
import AppNavBar from "@/components/AppNavBar.vue";
import SafeBottomAction from "@/components/safe-bottom-action.vue";
import { getCourse, getRule } from "@/api/backend";
const option = getCurrentPages().at(-1)?.options || {}; const id = option.id; const loading = ref(true); const course = ref({}); const sections = ref([]);
onMounted(load);
async function load() { if (!id) { loading.value = false; return; } try { const result = await getCourse(id); course.value = result?.course || result || {}; sections.value = normalize(course.value); } catch (_) { try { const result = await getRule(id); course.value = result || {}; sections.value = normalize(course.value); } catch (error) { uni.showToast({ title: error?.message || "规则加载失败", icon: "none" }); } } finally { loading.value = false; } }
function normalize(value) { let rows = value.sections || value.contentSections || value.chapters; if (typeof rows === "string") { try { rows = JSON.parse(rows); } catch (_) { rows = null; } } if (Array.isArray(rows) && rows.length) return rows.map(item => ({ title: item.title || item.name, content: String(item.content || item.body || item.text || ""), html: /<([a-z][\s\S]*?)>/i.test(String(item.content || item.body || "")) ? String(item.content || item.body) : "" })); const content = String(value.content || value.body || value.details || value.intro || ""); return content ? [{ title: value.title, content, html: /<([a-z][\s\S]*?)>/i.test(content) ? content : "" }] : []; }
function complete() { uni.showToast({ title: "学习完成", icon: "success" }); setTimeout(() => uni.navigateBack(), 500); }
</script>
<style scoped>
.page{min-height:100vh;background:#fff8e1}.content{height:calc(100vh - 176rpx);padding-bottom:40rpx;box-sizing:border-box}.hero{padding:32rpx 36rpx 22rpx;text-align:center}.hero text{display:block;color:#333;font-size:42rpx;font-weight:800;line-height:1.4}.hero text:first-child{background:linear-gradient(transparent 58%,#ffde59 58%)}.intro{margin:0 32rpx 34rpx;padding:28rpx;border-radius:24rpx;background:#fff;color:#555;font-size:28rpx;line-height:1.8;text-align:center;box-shadow:0 4rpx 18rpx rgba(180,140,0,.08)}.intro text{color:#e87900;font-weight:700}.pill{width:max-content;margin:0 auto 28rpx;padding:16rpx 48rpx;border-radius:999rpx;background:#ffe47a;color:#5a4100;font-size:29rpx;font-weight:700}.section{margin:0 24rpx 28rpx;overflow:hidden;border-radius:24rpx;background:#fff;box-shadow:0 4rpx 18rpx rgba(180,140,0,.08)}.section-title{display:block;padding:26rpx 30rpx;background:linear-gradient(#ffde59,#ffc81f);color:#5a4100;font-size:32rpx;font-weight:800}.section-body{display:block;padding:28rpx 30rpx;color:#555;font-size:28rpx;line-height:1.9;white-space:pre-wrap}.state{padding:120rpx 32rpx;color:#999;text-align:center}.done{width:100%;height:84rpx;border:0;border-radius:44rpx;background:#ff6b35;color:#fff;font-size:29rpx}
</style>
