<template>
  <view class="page">
    <AppNavBar title="答题测试" :show-back="true" />
    <view v-if="loading" class="state">题目加载中…</view>
    <scroll-view v-else-if="!finished" scroll-y class="content">
      <view class="quiz-header"><view class="progress"><view class="progress-fill" :style="{ width: `${progress}%` }" /></view><view class="progress-text"><text>第 {{ currentIndex + 1 }} / {{ questions.length }} 题</text><text>答对 {{ correctCount }} 题</text></view></view>
      <view v-if="currentQuestion" class="question-card"><text class="question-type">单选题</text><text class="question">{{ currentQuestion.content || currentQuestion.question || currentQuestion.title }}</text><text v-if="currentQuestion.tip" class="tip">{{ currentQuestion.tip }}</text><view v-for="option in currentQuestion.options" :key="option.value" class="option" :class="optionClass(option)" @click="choose(option.value)"><text class="circle">{{ option.value }}</text><text class="option-label">{{ option.label }}</text></view></view>
    </scroll-view>
    <scroll-view v-else scroll-y class="content"><view class="result-card"><text class="result-icon" :class="{ fail: !passed }">{{ passed ? "✓" : "!" }}</text><text class="result-title">{{ passed ? "恭喜你，考试通过" : "考试未通过" }}</text><text class="result-desc">答对 {{ correctCount }} / {{ questions.length }} 题</text><text class="result-tip">{{ passed ? "已获得接单资格，可以去找工作啦！" : "建议重新学习平台规则后再测试" }}</text></view></scroll-view>
    <SafeBottomAction><view class="footer-buttons"><template v-if="!finished"><button class="outline" @click="exit">退出测试</button><button class="primary" :disabled="selected === '' || submitting" @click="next">{{ submitting ? "提交中…" : currentIndex === questions.length - 1 ? "提交答卷" : "下一题" }}</button></template><template v-else><button class="outline" @click="restart">再测一次</button><button class="primary" @click="backClassroom">返回课堂</button></template></view></SafeBottomAction>
  </view>
</template>
<script setup>
import { computed, onMounted, ref } from "vue";
import AppNavBar from "@/components/AppNavBar.vue";
import SafeBottomAction from "@/components/safe-bottom-action.vue";
import { getWorkerClassroomQuiz, submitWorkerClassroomQuiz } from "@/api/backend";
const questions = ref([]); const currentIndex = ref(0); const answers = ref({}); const loading = ref(true); const submitting = ref(false); const finished = ref(false); const passed = ref(false); const correctCount = ref(0); const passScore = ref(60);
const currentQuestion = computed(() => questions.value[currentIndex.value]); const selected = computed(() => currentQuestion.value ? answers.value[currentQuestion.value.id] ?? "" : ""); const progress = computed(() => questions.value.length ? ((currentIndex.value + 1) / questions.value.length) * 100 : 0);
onMounted(load);
async function load() { try { const result = await getWorkerClassroomQuiz(); const data = result?.data || result || {}; passScore.value = Number(data.passScore || 60); const rows = data.questions || []; questions.value = rows.map((item, index) => ({ ...item, id: item.id || index, content: item.stem || item.content || item.question || item.title, options: normalizeOptions(item.options || item.choices) })); if (!questions.value.length) uni.showToast({ title: "后台暂未发布答题内容", icon: "none" }); } catch (error) { uni.showToast({ title: error?.message || "考试加载失败", icon: "none" }); } finally { loading.value = false; } }
function normalizeOptions(value) { if (typeof value === "string") { try { value = JSON.parse(value); } catch (_) { value = value.split("|"); } } if (Array.isArray(value)) return value.map((item, index) => typeof item === "object" ? { value: item.value || item.key || String.fromCharCode(65 + index), label: item.label || item.text || item.value } : { value: String.fromCharCode(65 + index), label: item }); return Object.entries(value || {}).map(([key, label]) => ({ value: key, label })); }
function choose(value) { answers.value[currentQuestion.value.id] = value; } function optionClass(option) { return { selected: selected.value === option.value }; }
async function next() { if (selected.value === "") return; if (currentIndex.value < questions.value.length - 1) { currentIndex.value += 1; return; } submitting.value = true; try { const result = await submitWorkerClassroomQuiz({ answers: answers.value }); correctCount.value = Number(result?.score ?? 0); passed.value = Boolean(result?.passed); finished.value = true; if (passed.value) uni.setStorageSync("workerQualified", true); } catch (error) { uni.showToast({ title: error?.message || "考试提交失败", icon: "none" }); } finally { submitting.value = false; } }
function restart() { answers.value = {}; currentIndex.value = 0; finished.value = false; correctCount.value = 0; passed.value = false; } function exit() { uni.navigateBack(); } function backClassroom() { uni.redirectTo({ url: "/pages/worker/classroom" }); }
</script>
<style scoped>
.page{min-height:100vh;background:#f5f5f5}.content{height:calc(100vh - 176rpx)}.quiz-header{padding:28rpx 32rpx;background:linear-gradient(135deg,#ffe4b5,#ffd59e)}.progress{height:12rpx;border-radius:8rpx;background:rgba(255,255,255,.65);overflow:hidden}.progress-fill{height:100%;border-radius:8rpx;background:#ff6b35}.progress-text{display:flex;justify-content:space-between;margin-top:14rpx;color:#8b4513;font-size:24rpx}.question-card,.result-card{margin:24rpx;padding:32rpx;border-radius:24rpx;background:#fff;box-shadow:0 4rpx 18rpx rgba(0,0,0,.05)}.question-type{display:block;color:#ff6b35;font-size:24rpx}.question{display:block;margin:18rpx 0 24rpx;color:#333;font-size:32rpx;font-weight:700;line-height:1.55}.tip{display:block;padding:18rpx;border-radius:12rpx;background:#fff8e6;color:#999;font-size:24rpx;line-height:1.5}.option{display:flex;align-items:center;gap:18rpx;margin-top:18rpx;padding:24rpx;border:2rpx solid transparent;border-radius:18rpx;background:#fafafa;color:#555}.option.selected{border-color:#ff6b35;background:#fff0e8;color:#ff6b35}.circle{width:42rpx;height:42rpx;line-height:42rpx;border:2rpx solid #ddd;border-radius:50%;text-align:center;font-size:23rpx}.selected .circle{border-color:#ff6b35}.option-label{font-size:27rpx;line-height:1.4}.footer-buttons{display:flex;gap:20rpx}.footer-buttons button{flex:1;height:84rpx;border-radius:44rpx;font-size:28rpx}.primary{border:0;background:#ff6b35;color:#fff}.outline{border:2rpx solid #ff6b35;background:#fff;color:#ff6b35}.primary[disabled]{background:#ffccb3}.result-card{text-align:center;padding:72rpx 32rpx}.result-icon{display:block;width:120rpx;height:120rpx;line-height:120rpx;margin:0 auto 24rpx;border-radius:50%;background:#e8f5e9;color:#4caf50;font-size:72rpx;font-weight:700}.result-icon.fail{background:#ffebee;color:#e53935}.result-title{display:block;color:#333;font-size:36rpx;font-weight:700}.result-desc{display:block;margin-top:20rpx;color:#ff6b35;font-size:30rpx}.result-tip{display:block;margin-top:18rpx;color:#888;font-size:25rpx}.state{padding:180rpx 32rpx;color:#999;text-align:center;font-size:28rpx}
</style>
