spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/kuaima?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: 11112222
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


jwt:
  secret: 7sK9dP2qR5zX8bN4vG1tL6cW3jF0hY7mA9sD2fJ5kQ8pZ1xV4bN7gT0lC3rH6jM9wS2dF5
  # access token 有效期（毫秒），3 天
  expiration: 259200000

wechat:
  appid: wx4c163632a2e19ea5
  secret: 14be11aeff46c668f888ac7bdd4a5388

# SpringDoc OpenAPI / Swagger 文档配置
springdoc:
  api-docs:
    enabled: false
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    display-request-duration: true
