package com.kuaima.app.controller.boss;
import java.util.*;import org.springframework.data.domain.*;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;
import com.kuaima.app.common.*;import com.kuaima.app.domain.points.service.BossPointsService;import com.kuaima.app.domain.user.constant.UserRole;import com.kuaima.app.security.model.LoginUser;import io.swagger.v3.oas.annotations.Operation;import io.swagger.v3.oas.annotations.tags.Tag;
@RestController @RequestMapping("/boss/points") @Tag(name="老板端-积分")
public class BossPointsController {
 private final BossPointsService service;public BossPointsController(BossPointsService s){service=s;}
 @GetMapping @Operation(summary="积分余额、套餐和规则") public Result<Map<String,Object>> overview(Authentication a){return Result.success(service.overview(boss(a)));}
 @PostMapping("/purchase") @Operation(summary="创建积分购买订单") public Result<Map<String,Object>> purchase(@RequestBody Map<String,Object>b,@RequestHeader(value="Idempotency-Key",required=false)String key,Authentication a){return Result.success(service.purchase(boss(a),longVal(b.get("packageId"),"packageId"),str(b.get("payChannel")),key));}
 @PostMapping("/purchase/{orderNo}/success") @Operation(summary="支付成功回调幂等入账") public Result<Map<String,Object>> purchaseSuccess(@PathVariable String orderNo,Authentication a){var o=service.markPaid(orderNo,boss(a));return Result.success(Map.of("orderNo",o.getOrderNo(),"status",o.getStatus(),"points",o.getPoints()));}
 @PostMapping("/gift") @Operation(summary="赠送积分给零工") public Result<Map<String,Object>> gift(@RequestBody Map<String,Object>b,@RequestHeader(value="Idempotency-Key",required=false)String key,Authentication a){return Result.success(service.gift(boss(a),longVal(b.get("workerId"),"workerId"),intVal(b.get("points"),"points"),key));}
 @GetMapping("/records") @Operation(summary="积分明细") public Result<List<Map<String,Object>>> records(@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,@RequestParam(defaultValue="ALL")String type,Authentication a){if(page<0||size<1||size>100)throw new IllegalArgumentException("page 或 size 参数无效");var p=service.records(boss(a),type,PageRequest.of(page,size,Sort.by(Sort.Direction.DESC,"timestamp")));return Result.success(p.getContent(),page,p.getTotalElements());}
 private Long boss(Authentication a){if(a!=null&&a.getPrincipal() instanceof LoginUser u&&u.id()!=null&&UserRole.BOSS.equals(u.role()))return u.id();throw new ForbiddenBusinessException("当前登录账号不是有效的老板账号");}private String str(Object v){return v==null?null:String.valueOf(v).trim().toUpperCase();}private Long longVal(Object v,String n){try{return v==null?null:Long.valueOf(String.valueOf(v));}catch(Exception e){throw new IllegalArgumentException(n+" 必须是整数");}}private Integer intVal(Object v,String n){try{return v==null?null:Integer.valueOf(String.valueOf(v));}catch(Exception e){throw new IllegalArgumentException(n+" 必须是整数");}}
}
