package com.kuaima.app.domain.points.service;
import static org.junit.jupiter.api.Assertions.*;import static org.mockito.Mockito.*;import java.math.BigDecimal;import java.util.Optional;import org.junit.jupiter.api.*;
import org.mockito.ArgumentCaptor;
import com.kuaima.app.admin.entity.PointPurchaseOrder;import com.kuaima.app.admin.repository.PointPurchaseOrderRepository;import com.kuaima.app.domain.points.entity.*;import com.kuaima.app.domain.points.repository.*;import com.kuaima.app.domain.user.constant.UserRole;import com.kuaima.app.domain.user.entity.User;import com.kuaima.app.domain.user.repository.UserRepository;
class BossPointsServiceTests {
 PointsAccountRepository accounts=mock(PointsAccountRepository.class);PointsFlowRepository flows=mock(PointsFlowRepository.class);PointsPackageRepository packages=mock(PointsPackageRepository.class);PointPurchaseOrderRepository orders=mock(PointPurchaseOrderRepository.class);PointsGiftRepository gifts=mock(PointsGiftRepository.class);UserRepository users=mock(UserRepository.class);BossPointsService service=new BossPointsService(accounts,flows,packages,orders,gifts,users);
 @Test void overviewShouldUseDatabasePackages(){PointsAccount a=new PointsAccount();a.setBalance(320);a.setRole(UserRole.BOSS);PointsPackage p=new PointsPackage();p.setId(1L);p.setPoints(1000);p.setPrice(1000);when(accounts.findByUserIdAndRole(7L,UserRole.BOSS)).thenReturn(Optional.of(a));when(packages.findByEnabledTrueOrderByPointsAsc()).thenReturn(java.util.List.of(p));var r=service.overview(7L);assertEquals(320,r.get("balance"));assertEquals(1,((java.util.List<?>)r.get("packages")).size());}
 @Test void giftShouldRejectInvalidPoints(){assertThrows(IllegalArgumentException.class,()->service.gift(7L,9L,50,"x"));}
 @Test void giftShouldTransferAndWriteRoleIsolatedFlows(){User worker=new User();worker.setId(9L);PointsAccount boss=new PointsAccount();boss.setUserId(7L);boss.setRole(UserRole.BOSS);boss.setBalance(1000);PointsAccount target=new PointsAccount();target.setUserId(9L);target.setRole(UserRole.USER);target.setBalance(20);when(users.findById(9L)).thenReturn(Optional.of(worker));when(gifts.findByIdempotencyKey("gift-1")).thenReturn(Optional.empty());when(accounts.findByUserIdAndRoleForUpdate(7L,UserRole.BOSS)).thenReturn(Optional.of(boss));when(accounts.findByUserIdAndRoleForUpdate(9L,UserRole.USER)).thenReturn(Optional.of(target));when(gifts.save(any())).thenAnswer(i->{PointsGift g=i.getArgument(0);g.setId(3L);return g;});service.gift(7L,9L,500,"gift-1");assertEquals(500,boss.getBalance());assertEquals(520,target.getBalance());ArgumentCaptor<PointsFlow> captor=ArgumentCaptor.forClass(PointsFlow.class);verify(flows,times(2)).save(captor.capture());assertEquals(java.util.List.of(UserRole.BOSS,UserRole.USER),captor.getAllValues().stream().map(PointsFlow::getRole).toList());}
 @Test void giftShouldAllowUnverifiedUserEvenWhenCurrentRoleIsBoss(){User worker=new User();worker.setId(9L);worker.setRole("BOSS");worker.setEnterpriseStatus("UNVERIFIED");PointsAccount boss=new PointsAccount();boss.setUserId(7L);boss.setRole(UserRole.BOSS);boss.setBalance(1000);PointsAccount target=new PointsAccount();target.setUserId(9L);target.setRole(UserRole.USER);target.setBalance(0);when(users.findById(9L)).thenReturn(Optional.of(worker));when(gifts.findByIdempotencyKey("gift-role-switch")).thenReturn(Optional.empty());when(accounts.findByUserIdAndRoleForUpdate(7L,UserRole.BOSS)).thenReturn(Optional.of(boss));when(accounts.findByUserIdAndRoleForUpdate(9L,UserRole.USER)).thenReturn(Optional.of(target));when(gifts.save(any())).thenAnswer(i->{PointsGift g=i.getArgument(0);g.setId(4L);return g;});service.gift(7L,9L,100,"gift-role-switch");assertEquals(900,boss.getBalance());assertEquals(100,target.getBalance());assertEquals(UserRole.USER,target.getRole());}
 @Test void giftShouldRejectLegacyApprovedEnterprise(){User worker=new User();worker.setId(9L);worker.setEnterpriseStatus("UNVERIFIED");worker.setCertType("ENTERPRISE");worker.setCertStatus("已通过");when(users.findById(9L)).thenReturn(Optional.of(worker));var error=assertThrows(IllegalArgumentException.class,()->service.gift(7L,9L,100,"gift-enterprise"));assertEquals("赠送对象不是有效零工",error.getMessage());verifyNoInteractions(accounts,flows,gifts);}
 @Test void markPaidShouldBeIdempotent(){PointPurchaseOrder o=new PointPurchaseOrder();o.setOrderNo("BP1");o.setPoints(1000L);o.setPointsGranted(true);when(orders.findByOrderNoAndBossId("BP1",7L)).thenReturn(Optional.of(o));assertSame(o,service.markPaid("BP1",7L));verifyNoInteractions(accounts,flows);}
 @Test void purchaseShouldCalculateFromPackage(){PointsPackage p=new PointsPackage();p.setId(1L);p.setPoints(1000);p.setPrice(1000);when(packages.findByIdAndEnabledTrue(1L)).thenReturn(Optional.of(p));when(orders.findByIdempotencyKey("p1")).thenReturn(Optional.empty());when(orders.save(any())).thenAnswer(i->i.getArgument(0));var r=service.purchase(7L,1L,"WECHAT","p1");assertEquals(1000,r.get("amount"));verify(orders).save(argThat(o->new BigDecimal("10.00").compareTo(o.getAmount())==0));}
}
