package com.kuaima.app.domain.points.service;

import java.math.BigDecimal;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;
import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
import com.kuaima.app.admin.entity.PointPurchaseOrder;import com.kuaima.app.admin.repository.PointPurchaseOrderRepository;
import com.kuaima.app.domain.points.entity.*;import com.kuaima.app.domain.points.repository.*;import com.kuaima.app.domain.user.constant.UserRole;import com.kuaima.app.domain.user.repository.UserRepository;import jakarta.persistence.EntityNotFoundException;

@Service
public class BossPointsService {
 private static final ZoneId ZONE=ZoneId.of("Asia/Shanghai");private final PointsAccountRepository accounts;private final PointsFlowRepository flows;private final PointsPackageRepository packages;private final PointPurchaseOrderRepository orders;private final PointsGiftRepository gifts;private final UserRepository users;
 public BossPointsService(PointsAccountRepository a,PointsFlowRepository f,PointsPackageRepository p,PointPurchaseOrderRepository o,PointsGiftRepository g,UserRepository u){accounts=a;flows=f;packages=p;orders=o;gifts=g;users=u;}
 @Transactional public Map<String,Object> overview(Long bossId){PointsAccount a=account(bossId,UserRole.BOSS);return Map.of("balance",balance(a),"packages",packages.findByEnabledTrueOrderByPointsAsc().stream().map(p->Map.of("id",p.getId(),"points",p.getPoints(),"price",p.getPrice(),"tag",p.getTag()==null?"":p.getTag(),"hot",Boolean.TRUE.equals(p.getHot()))).toList(),"rules",List.of("100积分=1元，积分不可兑换现金","赠送积分后不可撤回"));}
 @Transactional public Map<String,Object> purchase(Long bossId,Long packageId,String channel,String key){if(packageId==null)throw new IllegalArgumentException("packageId 不能为空");if(!Set.of("WECHAT","ALIPAY").contains(channel))throw new IllegalArgumentException("payChannel 只能是 WECHAT 或 ALIPAY");PointsPackage p=packages.findByIdAndEnabledTrue(packageId).orElseThrow(()->new EntityNotFoundException("积分套餐不存在: "+packageId));String idem=key==null||key.isBlank()?hash(bossId+"|"+packageId+"|"+channel+"|"+LocalDateTime.now(ZONE).format(DateTimeFormatter.ofPattern("yyyyMMddHHmm"))):key.trim();Optional<PointPurchaseOrder> old=orders.findByIdempotencyKey(idem);PointPurchaseOrder o;if(old.isPresent())o=old.get();else{o=new PointPurchaseOrder();o.setOrderNo("BP"+LocalDateTime.now(ZONE).format(DateTimeFormatter.ofPattern("yyyyMMddHHmmss"))+UUID.randomUUID().toString().substring(0,6).toUpperCase());o.setIdempotencyKey(idem);o.setBossId(bossId);o.setPoints(Long.valueOf(p.getPoints()));o.setAmount(BigDecimal.valueOf(p.getPrice(),2));o.setUnitPrice(o.getAmount().divide(BigDecimal.valueOf(p.getPoints()),4,java.math.RoundingMode.HALF_UP));o.setPayMethod("WECHAT".equals(channel)?"微信支付":"支付宝");o.setStatus("待支付");o.setPurchaseTime(LocalDateTime.now(ZONE));o.setPointsGranted(false);o=orders.save(o);}return Map.of("orderNo",o.getOrderNo(),"amount",p.getPrice(),"payParams",Map.of(),"status",o.getStatus());}
 @Transactional public PointPurchaseOrder markPaid(String orderNo,Long bossId){PointPurchaseOrder o=orders.findByOrderNoAndBossId(orderNo,bossId).orElseThrow(()->new EntityNotFoundException("积分购买订单不存在"));if(Boolean.TRUE.equals(o.getPointsGranted()))return o;PointsAccount a=lockedAccount(bossId,UserRole.BOSS);long after=(long)balance(a)+o.getPoints();if(after>Integer.MAX_VALUE)throw new IllegalArgumentException("积分余额超出系统上限");a.setBalance((int)after);accounts.save(a);flow(bossId,UserRole.BOSS,Math.toIntExact(o.getPoints()),"PURCHASE",after,o.getOrderNo(),"购买积分");o.setPointsGranted(true);o.setStatus("支付成功");return orders.save(o);}
 @Transactional public Map<String,Object> gift(Long bossId,Long workerId,Integer points,String key){if(workerId==null)throw new IllegalArgumentException("workerId 不能为空");if(points==null||points<100||points%100!=0)throw new IllegalArgumentException("赠送积分最低100且必须为100的整数倍");var worker=users.findById(workerId).orElseThrow(()->new EntityNotFoundException("零工不存在: "+workerId));if(UserRole.hasApprovedEnterprise(worker))throw new IllegalArgumentException("赠送对象不是有效零工");String idem=key==null||key.isBlank()?hash(bossId+"|"+workerId+"|"+points+"|"+LocalDateTime.now(ZONE).format(DateTimeFormatter.ofPattern("yyyyMMddHHmm"))):key.trim();var old=gifts.findByIdempotencyKey(idem);if(old.isPresent())return Map.of("giftId",old.get().getId(),"workerId",workerId,"points",points,"status","SUCCESS");PointsAccount boss=lockedAccount(bossId,UserRole.BOSS);if(balance(boss)<points)throw new IllegalArgumentException("积分余额不足");PointsAccount target=lockedAccount(workerId,UserRole.USER);boss.setBalance(balance(boss)-points);long workerAfter=(long)balance(target)+points;if(workerAfter>Integer.MAX_VALUE)throw new IllegalArgumentException("零工积分余额超出系统上限");target.setBalance((int)workerAfter);accounts.save(boss);accounts.save(target);PointsGift gift=new PointsGift();gift.setIdempotencyKey(idem);gift.setBossId(bossId);gift.setWorkerId(workerId);gift.setPoints(points);gift.setCreateTime(LocalDateTime.now(ZONE));gift=gifts.save(gift);String no="GIFT-"+gift.getId();flow(bossId,UserRole.BOSS,-points,"GIFT",balance(boss),no,"赠送积分给零工"+workerId);flow(workerId,UserRole.USER,points,"RECEIVED",workerAfter,no,"收到老板"+bossId+"赠送积分");return Map.of("giftId",gift.getId(),"workerId",workerId,"points",points,"status","SUCCESS");}
 public Page<Map<String,Object>> records(Long bossId,String type,Pageable pageable){String t=type==null?"ALL":type.toUpperCase();if(!Set.of("ALL","PURCHASE","CONSUME","GIFT","RECEIVED","EXPIRED").contains(t))throw new IllegalArgumentException("type 参数无效");return flows.findByUserIdAndRoleAndType(bossId,UserRole.BOSS,t,pageable).map(f->{Map<String,Object>m=new LinkedHashMap<>();m.put("id",f.getId());m.put("type",f.getBizType());m.put("points",f.getDelta());m.put("balanceAfter",f.getBalanceAfter());m.put("orderNo",f.getBizNo());m.put("remark",f.getRemark());m.put("time",f.getTimestamp());return m;});}
 private PointsAccount account(Long uid,String role){return accounts.findByUserIdAndRole(uid,role).orElseGet(()->{PointsAccount a=new PointsAccount();a.setUserId(uid);a.setRole(role);a.setBalance(0);return accounts.save(a);});}private PointsAccount lockedAccount(Long uid,String role){return accounts.findByUserIdAndRoleForUpdate(uid,role).orElseGet(()->account(uid,role));}private int balance(PointsAccount a){return a.getBalance()==null?0:a.getBalance();}private void flow(Long uid,String role,int delta,String type,long after,String no,String remark){PointsFlow f=new PointsFlow();f.setUserId(uid);f.setRole(role);f.setDelta(delta);f.setBizType(type);f.setBalanceAfter(Math.toIntExact(after));f.setBizNo(no);f.setRemark(remark);flows.save(f);}private String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
