package com.kuaima.app.admin.controller;
import java.math.BigDecimal;import java.util.*;import org.springframework.data.domain.*;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import com.alibaba.fastjson2.JSON;import com.kuaima.app.admin.entity.RewardCampaign;import com.kuaima.app.admin.repository.RewardGrantRepository;import com.kuaima.app.admin.service.AdminRewardService;import com.kuaima.app.common.*;import com.kuaima.app.security.model.LoginUser;import jakarta.persistence.EntityNotFoundException;import io.swagger.v3.oas.annotations.tags.Tag;
@RestController @RequestMapping("/admin/rewards") @Tag(name="后台-奖励金管理") public class AdminRewardController {private final AdminRewardService service;private final RewardGrantRepository grants;public AdminRewardController(AdminRewardService s,RewardGrantRepository g){service=s;grants=g;}
 @GetMapping public Result<List<Map<String,Object>>> list(@RequestParam(required=false)String status,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="10")int size,Authentication a){admin(a,false);if(status!=null&&!Set.of("待发放","已发放","已撤销").contains(status))throw new IllegalArgumentException("status 参数无效");if(page<0||size<1||size>100)throw new IllegalArgumentException("page 或 size 参数无效");var p=service.list(status,PageRequest.of(page,size));return Result.success(p.stream().map(this::view).toList(),page,p.getTotalElements());}
 @GetMapping("/stats") public Result<Map<String,Object>> stats(Authentication a){admin(a,false);return Result.success(service.stats());}
 @PostMapping public Result<Map<String,Object>> create(@RequestBody Map<String,Object>b,Authentication a){LoginUser u=admin(a,true);return Result.success(view(service.create(b,u.id(),u.username())));}
 @GetMapping("/{id}") public Result<Map<String,Object>> detail(@PathVariable Long id,Authentication a){admin(a,false);return Result.success(view(service.get(id)));}
 @PutMapping("/{id}/cancel") public Result<Map<String,Object>> cancel(@PathVariable Long id,Authentication a){admin(a,true);return Result.success(view(service.cancel(id)));}
 private Map<String,Object> view(RewardCampaign c){Map<String,Object>m=new LinkedHashMap<>();m.put("id",c.getId());m.put("rewardNo",c.getRewardNo());m.put("name",c.getName());m.put("target",c.getTarget());m.put("scope",c.getScope());m.put("users",c.getUsers()==null?List.of():JSON.parseArray(c.getUsers(),Long.class));m.put("count",c.getPlannedCount());m.put("amountMode",c.getAmountMode());m.put("amount",yuan(c.getAmount()));m.put("min",yuan(c.getMinAmount()));m.put("max",yuan(c.getMaxAmount()));m.put("total",yuan(c.getActualAmount()!=null&&c.getActualAmount()>0?c.getActualAmount():c.getTotalAmount()));m.put("status",c.getStatus());m.put("sendAt",c.getSendAt());m.put("createdAt",c.getCreatedAt());m.put("remark",c.getRemark());m.put("actualCount",c.getActualCount());m.put("actualAmount",yuan(c.getActualAmount()));m.put("failedCount",c.getFailedCount());m.put("errorMessage",c.getErrorMessage());return m;}private BigDecimal yuan(Long v){return v==null?null:BigDecimal.valueOf(v,2);}
 private LoginUser admin(Authentication a,boolean write){if(a==null||!(a.getPrincipal() instanceof LoginUser u)||u.role()==null||!u.role().startsWith("ADMIN_"))throw new ForbiddenBusinessException("仅管理员可操作");if(write&&u.role().endsWith("VIEWER"))throw new ForbiddenBusinessException("当前管理员无奖励金管理权限");return u;}}
