package com.kuaima.app.admin.controller;

import java.util.*; import java.math.BigDecimal; import java.math.RoundingMode;
import org.springframework.security.core.Authentication;
import org.springframework.web.bind.annotation.*;
import com.kuaima.app.admin.entity.*;
import com.kuaima.app.admin.repository.*;
import com.kuaima.app.common.*;
import com.kuaima.app.security.model.LoginUser;
import com.kuaima.app.admin.repository.PointPurchaseOrderRepository;
import java.time.*;

@RestController @RequestMapping("/admin/point-purchase/settings")
public class AdminPointSettingController {
 private final PointPackageSettingRepository packages; private final PointExchangeRuleRepository exchanges; private final PointEarnRuleRepository earns; private final PointPurchaseOrderRepository orders;
 public AdminPointSettingController(PointPackageSettingRepository p,PointExchangeRuleRepository e,PointEarnRuleRepository r,PointPurchaseOrderRepository o){packages=p;exchanges=e;earns=r;orders=o;}
 @GetMapping("/stats") public Result<Map<String,Object>> stats(Authentication a){admin(a,false);LocalDate m=LocalDate.now(ZoneId.of("Asia/Shanghai")).withDayOfMonth(1);LocalDateTime from=m.atStartOfDay(),to=m.plusMonths(1).atStartOfDay();Map<String,Object>x=new LinkedHashMap<>();x.put("enabledPackageCount",packages.findAllByOrderBySortDescIdAsc().stream().filter(p->Boolean.TRUE.equals(p.getEnabled())).count());x.put("soldPoints",orders.sumPaidPoints(from,to));x.put("soldAmount",orders.sumPaidAmount(from,to));x.put("enabledExchangeCount",exchanges.findAllByOrderBySortDescIdAsc().stream().filter(r->Boolean.TRUE.equals(r.getEnabled())).count());x.put("exchangedPoints",0);x.put("exchangedBossCount",0);x.put("exchangeRate",0);x.put("enabledEarnCount",earns.findAllByOrderBySortDescIdAsc().stream().filter(r->Boolean.TRUE.equals(r.getEnabled())).count());x.put("earnedPoints",0);x.put("earnedWorkerCount",0);x.put("earnActiveRate",0);return Result.success(x);}
 @GetMapping("/packages") public Result<List<Map<String,Object>>> packages(Authentication a){admin(a,false);return Result.success(packages.findAllByOrderBySortDescIdAsc().stream().map(this::pkg).toList());}
 @PostMapping("/packages") public Result<Map<String,Object>> savePackage(@RequestBody Map<String,Object>b,Authentication a){LoginUser u=admin(a,true);Long id=longVal(b.get("id"));String name=text(b,"name");if(name==null||name.length()<1||name.length()>20)throw new IllegalArgumentException("name 必填且长度1-20");Long points=longVal(b.get("points"));if(points==null||points<1)throw new IllegalArgumentException("points 必须是正整数，最少1积分");BigDecimal price=priceVal(b.get("price"));if(price==null||price.compareTo(new BigDecimal("0.01"))<0)throw new IllegalArgumentException("price 最低为0.01元");if(price.scale()>2)throw new IllegalArgumentException("price 最多支持两位小数");if(packages.existsByNameAndIdNot(name,id==null?0L:id))throw new IllegalArgumentException("套餐名称已存在");PointPackageSetting p=id==null?new PointPackageSetting():packages.findById(id).orElseThrow(()->new jakarta.persistence.EntityNotFoundException("积分套餐不存在"));p.setName(name);p.setSub(text(b,"sub"));p.setPoints(points);p.setPrice(price.setScale(2, RoundingMode.UNNECESSARY));p.setOriginalPrice(text(b,"originalPrice"));p.setSave(text(b,"save"));p.setRec(boolVal(b.get("rec")));p.setSort(intVal(b.get("sort"),0));p.setEnabled(boolVal(b.get("enabled")));p.setOperatorId(u.id());p.setOperatorName(u.username());return Result.success(pkg(packages.save(p)));}
 @GetMapping("/exchange-rules") public Result<List<Map<String,Object>>> exchange(Authentication a){admin(a,false);return Result.success(exchanges.findAllByOrderBySortDescIdAsc().stream().map(this::rule).toList());}
 @PostMapping("/exchange-rules") public Result<Map<String,Object>> saveExchange(@RequestBody Map<String,Object>b,Authentication a){return Result.success(rule(saveRule(b,admin(a,true),true)));}
 @PutMapping("/exchange-rules/{id}/toggle") public Result<Map<String,Object>> toggleExchange(@PathVariable Long id,Authentication a){LoginUser u=admin(a,true);PointExchangeRule r=exchanges.findById(id).orElseThrow(()->new jakarta.persistence.EntityNotFoundException("兑换规则不存在"));r.setEnabled(!Boolean.TRUE.equals(r.getEnabled()));r.setOperatorId(u.id());r.setOperatorName(u.username());return Result.success(rule(exchanges.save(r)));}
 @GetMapping("/earn-rules") public Result<List<Map<String,Object>>> earn(Authentication a){admin(a,false);return Result.success(earns.findAllByOrderBySortDescIdAsc().stream().map(this::rule).toList());}
 @PostMapping("/earn-rules") public Result<Map<String,Object>> saveEarn(@RequestBody Map<String,Object>b,Authentication a){return Result.success(rule(saveRule(b,admin(a,true),false)));}
 @PutMapping("/earn-rules/{id}/toggle") public Result<Map<String,Object>> toggleEarn(@PathVariable Long id,Authentication a){LoginUser u=admin(a,true);PointEarnRule r=earns.findById(id).orElseThrow(()->new jakarta.persistence.EntityNotFoundException("获取规则不存在"));r.setEnabled(!Boolean.TRUE.equals(r.getEnabled()));r.setOperatorId(u.id());r.setOperatorName(u.username());return Result.success(rule(earns.save(r)));}
 private Object saveRule(Map<String,Object>b,LoginUser u,boolean ex){String n=text(b,"name"),rate=text(b,"rate");if(n==null||n.isBlank()||n.length()>50)throw new IllegalArgumentException("name 必填");if(rate==null||rate.isBlank())throw new IllegalArgumentException("rate 必填");Long id=longVal(b.get("id"));if(ex){PointExchangeRule r=id==null?new PointExchangeRule():exchanges.findById(id).orElseThrow(()->new jakarta.persistence.EntityNotFoundException("兑换规则不存在"));fill(r,b,u);return exchanges.save(r);}PointEarnRule r=id==null?new PointEarnRule():earns.findById(id).orElseThrow(()->new jakarta.persistence.EntityNotFoundException("获取规则不存在"));fill(r,b,u);return earns.save(r);}
 private void fill(Object o,Map<String,Object>b,LoginUser u){String n=text(b,"name"),rate=text(b,"rate");if(o instanceof PointExchangeRule r){r.setName(n);r.setSub(text(b,"sub"));r.setIcon(text(b,"icon"));r.setIconColor(text(b,"iconColor"));r.setRate(rate);r.setLimit(text(b,"limit"));r.setCond(text(b,"cond"));r.setRuleCode(text(b,"ruleCode"));r.setFormula(text(b,"formula"));r.setSort(intVal(b.get("sort"),0));r.setEnabled(boolVal(b.get("enabled")));r.setOperatorId(u.id());r.setOperatorName(u.username());}else{PointEarnRule r=(PointEarnRule)o;r.setName(n);r.setSub(text(b,"sub"));r.setIcon(text(b,"icon"));r.setIconColor(text(b,"iconColor"));r.setRate(rate);r.setLimit(text(b,"limit"));r.setCond(text(b,"cond"));r.setRuleCode(text(b,"ruleCode"));r.setFormula(text(b,"formula"));r.setSort(intVal(b.get("sort"),0));r.setEnabled(boolVal(b.get("enabled")));r.setOperatorId(u.id());r.setOperatorName(u.username());}}
 private Map<String,Object> pkg(PointPackageSetting p){Map<String,Object>m=new LinkedHashMap<>();m.put("id",p.getId());m.put("name",p.getName());m.put("sub",p.getSub());m.put("points",p.getPoints());m.put("price",p.getPrice());m.put("originalPrice",p.getOriginalPrice());m.put("save",p.getSave());m.put("rec",p.getRec());m.put("sort",p.getSort());m.put("enabled",p.getEnabled());m.put("createdAt",p.getCreatedAt());m.put("updatedAt",p.getUpdatedAt());return m;}
 private Map<String,Object> rule(Object o){Map<String,Object>m=new LinkedHashMap<>();if(o instanceof PointExchangeRule r){m.put("id",r.getId());m.put("name",r.getName());m.put("sub",r.getSub());m.put("icon",r.getIcon());m.put("iconColor",r.getIconColor());m.put("rate",r.getRate());m.put("limit",r.getLimit());m.put("cond",r.getCond());m.put("sort",r.getSort());m.put("enabled",r.getEnabled());}else{PointEarnRule r=(PointEarnRule)o;m.put("id",r.getId());m.put("name",r.getName());m.put("sub",r.getSub());m.put("icon",r.getIcon());m.put("iconColor",r.getIconColor());m.put("rate",r.getRate());m.put("limit",r.getLimit());m.put("cond",r.getCond());m.put("sort",r.getSort());m.put("enabled",r.getEnabled());}return m;}
 private LoginUser admin(Authentication a,boolean w){if(a==null||!(a.getPrincipal() instanceof LoginUser u)||u.role()==null||!u.role().startsWith("ADMIN_"))throw new ForbiddenBusinessException("仅管理员可操作");if(w&&u.role().endsWith("VIEWER"))throw new ForbiddenBusinessException("当前管理员无积分管理权限");return u;}
 private String text(Map<String,Object>b,String k){Object v=b.get(k);return v==null?null:String.valueOf(v).trim();} private Long longVal(Object v){if(v==null)return null;try{return Long.valueOf(String.valueOf(v));}catch(Exception e){throw new IllegalArgumentException("数值参数无效");}} private BigDecimal priceVal(Object v){if(v==null)return null;try{return new BigDecimal(String.valueOf(v).trim());}catch(Exception e){throw new IllegalArgumentException("price 必须是金额");}} private int intVal(Object v,int d){Long n=longVal(v);return n==null?d:Math.toIntExact(n);} private Boolean boolVal(Object v){return v==null?Boolean.TRUE:Boolean.valueOf(String.valueOf(v));}
}
