package com.kuaima.app.admin.controller;
import java.math.BigDecimal;import java.util.*;import org.springframework.data.domain.*;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import com.alibaba.fastjson2.JSON;import com.kuaima.app.admin.entity.RewardCampaign;import com.kuaima.app.admin.repository.RewardGrantRepository;import com.kuaima.app.admin.service.AdminRewardService;import com.kuaima.app.common.*;import com.kuaima.app.security.model.LoginUser;import com.kuaima.app.domain.user.constant.UserRole;import com.kuaima.app.domain.user.entity.User;import com.kuaima.app.domain.user.repository.UserRepository;import jakarta.persistence.EntityNotFoundException;import io.swagger.v3.oas.annotations.tags.Tag;
@RestController @RequestMapping("/admin/rewards") @Tag(name="后台-奖励金管理") public class AdminRewardController {private final AdminRewardService service;private final RewardGrantRepository grants;private final UserRepository users;public AdminRewardController(AdminRewardService s,RewardGrantRepository g,UserRepository u){service=s;grants=g;users=u;}
 @GetMapping public Result<List<Map<String,Object>>> list(@RequestParam(required=false)String status,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="10")int size,Authentication a){admin(a,false);if(status!=null&&!Set.of("待发放","已发放","已撤销").contains(status))throw new IllegalArgumentException("status 参数无效");if(page<0||size<1||size>100)throw new IllegalArgumentException("page 或 size 参数无效");var p=service.list(status,PageRequest.of(page,size));return Result.success(p.stream().map(this::view).toList(),page,p.getTotalElements());}
 @GetMapping("/stats") public Result<Map<String,Object>> stats(Authentication a){admin(a,false);return Result.success(service.stats());}
 @GetMapping("/recipients") public Result<List<Map<String,Object>>> recipients(@RequestParam String target,@RequestParam(required=false)String keyword,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="20")int size,Authentication a){admin(a,false);String normalized=target==null?"":target.trim();if(page<0||size<1||size>100)throw new IllegalArgumentException("page 或 size 参数无效");String kw=keyword==null||keyword.isBlank()?null:keyword.trim();Pageable pageable=PageRequest.of(page,size,Sort.by(Sort.Direction.DESC,"id"));Page<User> rows=switch(normalized){case "老板","BOSS"->users.searchBossIdentityRecipients(kw,pageable);case "零工","USER"->users.searchWorkerIdentityRecipients(kw,pageable);case "全部用户","ALL"->users.searchRecipients(null,kw,pageable);default->throw new IllegalArgumentException("target 只能是老板、零工或全部用户");};return Result.success(rows.map(this::recipient).getContent(),page,rows.getTotalElements());}
 @PostMapping public Result<Map<String,Object>> create(@RequestBody Map<String,Object>b,Authentication a){LoginUser u=admin(a,true);return Result.success(view(service.create(b,u.id(),u.username())));}
 @GetMapping("/{id}") public Result<Map<String,Object>> detail(@PathVariable Long id,Authentication a){admin(a,false);return Result.success(view(service.get(id)));}
 @PutMapping("/{id}/cancel") public Result<Map<String,Object>> cancel(@PathVariable Long id,Authentication a){admin(a,true);return Result.success(view(service.cancel(id)));}
 private Map<String,Object> view(RewardCampaign c){Map<String,Object>m=new LinkedHashMap<>();m.put("id",c.getId());m.put("rewardNo",c.getRewardNo());m.put("name",c.getName());m.put("target",c.getTarget());m.put("scope",c.getScope());m.put("users",c.getUsers()==null?List.of():JSON.parseArray(c.getUsers(),Long.class));m.put("count",c.getPlannedCount());m.put("amountMode",c.getAmountMode());m.put("amount",yuan(c.getAmount()));m.put("min",yuan(c.getMinAmount()));m.put("max",yuan(c.getMaxAmount()));m.put("total",yuan(c.getActualAmount()!=null&&c.getActualAmount()>0?c.getActualAmount():c.getTotalAmount()));m.put("status",c.getStatus());m.put("sendAt",c.getSendAt());m.put("createdAt",c.getCreatedAt());m.put("remark",c.getRemark());m.put("actualCount",c.getActualCount());m.put("actualAmount",yuan(c.getActualAmount()));m.put("failedCount",c.getFailedCount());m.put("errorMessage",c.getErrorMessage());return m;}private BigDecimal yuan(Long v){return v==null?null:BigDecimal.valueOf(v,2);}
 private Map<String,Object> recipient(User u){Map<String,Object>m=new LinkedHashMap<>();m.put("id",u.getId());m.put("nickname",safe(u.getNickname()));m.put("realName",safe(u.getRealName()));m.put("username",safe(u.getUsername()));m.put("phone",maskPhone(u.getPhone()));m.put("identity",UserRole.isBossIdentity(u)?UserRole.BOSS:UserRole.USER);m.put("loginRole",u.getRole());m.put("companyName",safe(u.getCompanyName()));m.put("status",safe(u.getStatus()));return m;}private String safe(String v){return v==null?"":v;}private String maskPhone(String p){if(p==null||p.length()<7)return safe(p);return p.substring(0,3)+"****"+p.substring(p.length()-4);}
 private LoginUser admin(Authentication a,boolean write){if(a==null||!(a.getPrincipal() instanceof LoginUser u)||u.role()==null||!u.role().startsWith("ADMIN_"))throw new ForbiddenBusinessException("仅管理员可操作");if(write&&u.role().endsWith("VIEWER"))throw new ForbiddenBusinessException("当前管理员无奖励金管理权限");return u;}}
